name: "test VS 2019"

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Install checkout
      uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - name: Create Solution
      uses: Bassman2/create-solution@v1
      with:
        name: TestSolution
        projects: 'Tests\\DemoCS48\\DemoCS48.csproj, Tests\\DemoCS50\\DemoCS50.csproj'       
        
    - name: Test
      run: type TestSolution.sln
      shell: cmd
      
    - name: Build solution
      run: msbuild TestSolution.sln /p:configuration="Release" /m /verbosity:minimal
